# Generated by Django 3.2.4 on 2021-06-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='sno',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
