# Generated by Django 3.2.4 on 2021-06-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StpApp', '0003_alter_regform_aadhar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tusername', models.CharField(max_length=60)),
                ('treview1', models.FileField(default='', upload_to='treview1')),
                ('treview2', models.FileField(default='', upload_to='treview2')),
                ('treview3', models.FileField(default='', upload_to='treview3')),
            ],
        ),
    ]
