# Generated by Django 3.2.4 on 2021-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StpApp', '0005_auto_20210608_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tupload',
            name='treview1',
            field=models.FileField(default='', upload_to='treview1'),
        ),
        migrations.AlterField(
            model_name='tupload',
            name='treview2',
            field=models.FileField(default='', upload_to='treview2'),
        ),
        migrations.AlterField(
            model_name='tupload',
            name='treview3',
            field=models.FileField(default='', upload_to='treview3'),
        ),
    ]
