# Generated by Django 3.2.4 on 2021-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StpApp', '0008_studdata_studusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studdata',
            name='R1Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studdata',
            name='R2Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studdata',
            name='R3Marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studdata',
            name='StudTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
